[package]
name = "zoxide"
version = "0.4.3"
authors = ["Ajeet D'Souza <98ajeet@gmail.com>"]
description = "A faster way to navigate your filesystem"
repository = "https://github.com/ajeetdsouza/zoxide/"
edition = "2018"
keywords = ["cli"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"

[dependencies]
anyhow = "1.0.32"
askama = { version = "0.10.3", default-features = false }
bincode = "1.3.1"
clap = "3.0.0-beta.2"
dirs-next = "1.0.2"
dunce = "1.0.1"
glob = "0.3.0"
once_cell = "1.4.1"
ordered-float = "2.0.0"
serde = { version = "1.0.116", features = ["derive"] }
tempfile = "3.1.0"

[target.'cfg(windows)'.dependencies]
rand = "0.7.3"

[target.'cfg(unix)'.dev-dependencies]
assert_cmd = "1.0.1"

[profile.release]
codegen-units = 1
lto = true
