[package]
name = "zoxide"
version = "0.4.3"
authors = ["Ajeet D'Souza <98ajeet@gmail.com>"]
description = "A faster way to navigate your filesystem"
repository = "https://github.com/ajeetdsouza/zoxide/"
edition = "2018"
keywords = ["cli"]
categories = ["command-line-utilities", "filesystem"]
license = "MIT"

[dependencies]
anyhow = "1.0.32"
clap = "3.0.0-beta.2"
dirs-next = "1.0.2"
dunce = "1.0.1"
glob = "0.3.0"
once_cell = "1.4.1"
zoxide-engine = { path = "crates/zoxide-engine" }
zoxide-shell = { path = "crates/zoxide-shell" }

[workspace]

[profile.release]
codegen-units = 1
lto = true
