name: cargo-test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt update
      - run: sudo apt install wget apt-transport-https
      - run: wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
      - run: sudo dpkg -i packages-microsoft-prod.deb
      - run: sudo apt update
      - run: sudo add-apt-repository universe
      - run: sudo apt install bash dash fish powershell shellcheck xonsh zsh
      - run: sudo snap install shfmt
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
